version: "3.9"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres # Not a real password
      DB_NAME: app
      DB_SERVER: localhost
  db:
    extends:
      file: docker-compose.db.yml
      service: db
volumes:
  db_data:
    driver: local